export const siteConfig = {
  name: "Michael Serrano - Machine Learning Engineer & Researcher",
  authorName: "Michael Serrano",
  username: "michaelserrano",
  description:
    "MIT MEng student in Computer Science, Economics, and Data Science. Machine Learning Engineer & Researcher specializing in scalable ML pipelines, agentic tools, and full-stack AI development.",
  url: "https://michaelserrano.com",
  links: {
    github: "https://github.com/michaelyserrano/",
    linkedin: "https://linkedin.com/in/michael-y-serrano",
  },
  resumePdfUrl:
    "https://drive.google.com/file/d/1YW4H2cLcjUHJ6rLCa4HOr_pls7H2qJ_i/view?usp=sharing",
  contactEmail: "michaelyserrano@gmail.com",
  ogImage: "/opengraph-image.png",
  iconIco: "/favicon.ico",
  logoIcon: "/favicon.ico",
  keywords: [
    "Michael Serrano",
    "Machine Learning Engineer",
    "ML Researcher",
    "MIT",
    "CSAIL",
    "Roblox",
    "Python",
    "PyTorch",
    "TensorFlow",
    "Full Stack",
    "TypeScript",
    "React",
    "AI Development",
    "Data Science",
    "Tech Portfolio",
  ],
};
