export const siteConfig = {
  name: "Michael Serrano - Machine Learning Engineer & Researcher",
  authorName: "Michael Serrano",
  username: "michaelserrano",
  description:
    "MIT MEng in Computer Science, Economics, and Data Science (Course 6-14), with a double major BS in Physics (Course 8). Machine Learning Engineer & Researcher specializing in scalable ML pipelines, agentic tools, and full-stack AI development.",
  url: "https://michaelserrano.com",
  links: {
    github: "https://github.com/michaelyserrano/",
    linkedin: "https://linkedin.com/in/michael-y-serrano",
  },
  resumePdfUrl:
    "https://github.com/michaelyserrano/michaelyserrano.github.io/raw/main/resume/resume.pdf",
  contactEmail: "michaelyserrano@gmail.com",
  ogImage: "/logo.png",
  /** Cache-bust (?v=2) so browsers fetch the updated favicon instead of serving the old one. */
  iconIco: "/logo.png?v=2",
  logoIcon: "/logo.png?v=2",
  keywords: [
    "Michael Serrano",
    "Machine Learning Engineer",
    "ML Researcher",
    "MIT",
    "CSAIL",
    "Roblox",
    "Rindler",
    "Savaal",
    "Charak",
    "ConceptQ",
    "Python",
    "PyTorch",
    "TensorFlow",
    "Full Stack",
    "TypeScript",
    "React",
    "Go",
    "Rust",
    "AI Development",
    "Data Science",
    "Physics",
    "Tech Portfolio",
  ],
};
